# -*- coding: utf-8 -*-
"""Building a sequential model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MCwt2v2xTCUrHJtKbzUZ2v3k5cwhk4lm
"""

from google.colab import drive
drive.mount('gdrive')

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Softmax, Conv2D, MaxPooling2D

model = Sequential([
    Flatten(input_shape=(20, 20)),
    Dense(16, activation="relu"),
    Dense(16, activation="relu"),
    Dense(10, activation="softmax")
])

model.summary()

model1 = Sequential([
    Conv2D(16, (3,3), strides=2, padding="SAME", activation="relu", input_shape=(28,28,1)),
    MaxPooling2D((3,3)),
    Flatten(),
    Dense(10, activation='softmax')
])

model1.summary()