# -*- coding: utf-8 -*-
"""Hello googleColab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16iD2JoDXnkJuOLM2fbpNjSQecweOC0yS
"""

import tensorflow as tf

from google.colab import drive
drive.mount('gdrive')

myfile = open('gdrive/MyDrive/Colab Notebooks/TensorFlow specialization/Hello googleColab!.txt')
print(myfile.read())

!ls

!pip install numpy