# -*- coding: utf-8 -*-
"""The compile method

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JctSfp5HhhcGtPMBtJHrrTJM1rUGjOnl

#The compile method
"""

from google.colab import drive
drive.mount('gdrive')

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense, Softmax

model = Sequential([
    Flatten(input_shape=(20, 20)),
    Dense(16, activation='relu'),
    Dense(16, activation='relu'),
    Dense(10, activation='softmax')
])

model.summary()

opt = tf.keras.optimizers.Adam(learning_rate=0.005)
acc = tf.keras.metrics.SparseCategoricalAccuracy()
mae = tf.keras.metrics.MeanAbsoluteError()
l = tf.keras.losses.SparseCategoricalCrossentropy()

model.compile(optimizer=opt,
              loss=l,
              metrics=[acc, mae])

print(model.loss)
print(model.optimizer)
print(model.metrics)
print(model.optimizer.lr)